trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/README.md

pr: none

pool:
  vmImage: 'windows-latest'
steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'module'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'module'
    downloadPath: '$(System.DefaultWorkingDirectory)\ADSSQLNotebook'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Move files to a module folder
      # Publish the Module to the PowerShell Gallery
      Publish-Module -Path $(System.DefaultWorkingDirectory)\ADSSQLNotebook -NuGetApiKey $(GALLERYPAT) -verbose