trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/README.md

pr: none

pool:
  vmImage: 'windows-latest'
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Move files to a module folder
      New-Item $(System.DefaultWorkingDirectory)\ADSSQLNotebook -ItemType Directory
      Move-Item -Path $(System.DefaultWorkingDirectory) -Destination $(System.DefaultWorkingDirectory)\ADSSQLNotebook
      # Publish the Module to the PowerShell Gallery
      Publish-Module -Path $(System.DefaultWorkingDirectory)\ADSSQLNotebook -NuGetApiKey $(GALLERYPAT) -verbose