trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/README.md

pr: none

pool:
  vmImage: 'windows-latest'
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Import-MOdule .\ADSSQLNotebook.psd1
      # Publish the Module to the PowerShell Gallery
      Publish-Module -Name ADSSQLNotebook -NuGetApiKey $(GALLERYPAT) -verbose