trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      PowerShell script: 
      Publish-Module -Name ADSSQLNotebook -NuGetApiKey $env:GALLERYPAT -verbose


